pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'rgp-game-load-test'

include ':core'
include ':games:silkroad'
include ':games:bonanza'
include ':games:naga777'
include ':games:mutantmerge'
include ':games:zeroday'
include ':games:apsara'
include ':games:candy'
include ':games:colosseum'
include ':games:nagas-treasure'

// To enable another game, drop its directory under games/<name>/ and uncomment here.
// include ':games:fruit-respin-mania'
// include ':games:last-guardian-angkor'
