package com.rgp.loadtest.core.utils;

import com.rgp.loadtest.core.config.SlaConfig;
import com.rgp.loadtest.core.config.SlaConfigLoader;

/**
 * Production-gate SLA thresholds shared across all games.
 *
 * <p>Values are loaded from {@code config/sla-thresholds.yml} at JVM start via {@link
 * SlaConfigLoader}. To change thresholds, **edit the YAML — do not edit this file**.
 *
 * <p>Build fails (via Gatling Simulation assertions) if a game breaches PR-4 / PR-5.
 */
public final class SlaConstants {

  private static final SlaConfig CONFIG = SlaConfigLoader.load();

  /** PR-4: mean response time threshold (ms). */
  public static final int PR4_MEAN_RESPONSE_MS_MAX = CONFIG.pr4MeanResponseMsMax;

  /** PR-5: error rate threshold (%). */
  public static final double PR5_ERROR_PERCENT_MAX = CONFIG.pr5ErrorPercentMax;

  /** Wall-clock safety buffer (min) added to {@code maxDuration} so VUs aren't killed at the wire. */
  public static final int MAX_DURATION_BUFFER_MIN = CONFIG.maxDurationBufferMin;

  private SlaConstants() {}
}
